apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shipmentsstatestore
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: shipmentstore
  - name: accountKey
    value: "<Value here>"
  - name: tableName
    value: shipments
  - name: cosmosDbMode
    value: false
scopes:
- shipments-backend-processor    